// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class SecondaryFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpiWJG1Sfjw0ziyCoICDCyXyIJXCVE53U',
    appId: '1:752360497277:web:f419bd7b37b282459e5114',
    messagingSenderId: '752360497277',
    projectId: 'senzepact',
    authDomain: 'senzepact.firebaseapp.com',
    databaseURL:
        'https://senzepact-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'senzepact.appspot.com',
    measurementId: 'G-GWRB91MTCC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUNstHkDGNnViALD7bgFy0Dh_6YMHDjhY',
    appId: '1:752360497277:android:844d1d4df315df489e5114',
    messagingSenderId: '752360497277',
    projectId: 'senzepact',
    databaseURL:
        'https://senzepact-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'senzepact.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVtk9xwZzZrncUCjP-Wq0FISripFtZV2w',
    appId: '1:752360497277:ios:2530cab0591ba3d69e5114',
    messagingSenderId: '752360497277',
    projectId: 'senzepact',
    databaseURL:
        'https://senzepact-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'senzepact.appspot.com',
    iosClientId:
        '752360497277-f5a8jesp08brkl6g4asstj802nmshvi2.apps.googleusercontent.com',
    iosBundleId: 'com.senzehub.senzepact',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVtk9xwZzZrncUCjP-Wq0FISripFtZV2w',
    appId: '1:752360497277:ios:f40da7dc94c768a99e5114',
    messagingSenderId: '752360497277',
    projectId: 'senzepact',
    databaseURL:
        'https://senzepact-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'senzepact.appspot.com',
    iosClientId:
        '752360497277-152od26tmat7u9qem9rkgilat7p9uvs6.apps.googleusercontent.com',
    iosBundleId: 'com.senzehub.senzefind.newprojname',
  );
}
