// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJM_BZR4TEHFXIBIT935AeHt2sfDlPTDg',
    appId: '1:1059865400059:android:d0d8a9a81b49f91f8a965e',
    messagingSenderId: '1059865400059',
    projectId: 'senzelife',
    databaseURL: 'https://senzelife-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'senzelife.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzbKsUSYO-OyBV7yCGEr_xYflHCxem8u8',
    appId: '1:1059865400059:ios:f9edcb0777b937c98a965e',
    messagingSenderId: '1059865400059',
    projectId: 'senzelife',
    databaseURL: 'https://senzelife-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'senzelife.appspot.com',
    iosClientId: '1059865400059-44miosak5pclcjom0dovqp5ncgp7amku.apps.googleusercontent.com',
    iosBundleId: 'com.senzehub.senzelife',
  );

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyCD2gWInt0Ew-iEe4KzyIG0Gl3nFZ8EfnM",
      authDomain: "senzelife.firebaseapp.com",
      databaseURL: "https://senzelife-default-rtdb.asia-southeast1.firebasedatabase.app",
      projectId: "senzelife",
      storageBucket: "senzelife.appspot.com",
      messagingSenderId: "1059865400059",
      appId: "1:1059865400059:web:b0418721d3aac3588a965e"
  );
}
